// Automatically generated by MockGen. DO NOT EDIT!
// Source: router/router.go

package mock_router

import (
	gomock "github.com/golang/mock/gomock"
	mux "github.com/gorilla/mux"
	http "net/http"
)

// Mock of Router interface
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *_MockRouterRecorder
}

// Recorder for MockRouter (not exported)
type _MockRouterRecorder struct {
	mock *MockRouter
}

func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &_MockRouterRecorder{mock}
	return mock
}

func (_m *MockRouter) EXPECT() *_MockRouterRecorder {
	return _m.recorder
}

func (_m *MockRouter) HandleFunc(path string, f func(http.ResponseWriter, *http.Request)) *mux.Route {
	ret := _m.ctrl.Call(_m, "HandleFunc", path, f)
	ret0, _ := ret[0].(*mux.Route)
	return ret0
}

func (_mr *_MockRouterRecorder) HandleFunc(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HandleFunc", arg0, arg1)
}
