// Automatically generated by MockGen. DO NOT EDIT!
// Source: mux/router.go

package mock_mux

import (
	gomock "github.com/golang/mock/gomock"
	http "net/http"
)

// Mock of Router interface
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *_MockRouterRecorder
}

// Recorder for MockRouter (not exported)
type _MockRouterRecorder struct {
	mock *MockRouter
}

func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &_MockRouterRecorder{mock}
	return mock
}

func (_m *MockRouter) EXPECT() *_MockRouterRecorder {
	return _m.recorder
}

func (_m *MockRouter) POST(path string, f func(http.ResponseWriter, *http.Request)) {
	_m.ctrl.Call(_m, "POST", path, f)
}

func (_mr *_MockRouterRecorder) POST(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "POST", arg0, arg1)
}

func (_m *MockRouter) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	_m.ctrl.Call(_m, "ServeHTTP", w, req)
}

func (_mr *_MockRouterRecorder) ServeHTTP(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ServeHTTP", arg0, arg1)
}
